name: qr_scanner
description: Plugin, which provides QR code scanner and camera preview.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: cz.bcx.qrscanner
    pluginClass: QrScannerPlugin